services:
  - type: web
    name: meeting-scheduler-csharp
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ASPNETCORE_URLS
        value: http://+:10000
